CVDEV/force-app/main/default/objects/Customer_Reading__c/Customer_Reading__c.object-meta.xml
<CustomObject>
    <label>Customer Reading</label>
    <nameField>
        <label>Customer Reading Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_10__c.field-meta.xml
<CustomField>
    <fullName>Reading_10__c</fullName>
    <label>Reading 10</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_11__c.field-meta.xml
<CustomField>
    <fullName>Reading_11__c</fullName>
    <label>Reading 11</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_12__c.field-meta.xml
<CustomField>
    <fullName>Reading_12__c</fullName>
    <label>Reading 12</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_13__c.field-meta.xml
<CustomField>
    <fullName>Reading_13__c</fullName>
    <label>Reading 13</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_14__c.field-meta.xml
<CustomField>
    <fullName>Reading_14__c</fullName>
    <label>Reading 14</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_15__c.field-meta.xml
<CustomField>
    <fullName>Reading_15__c</fullName>
    <label>Reading 15</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_16__c.field-meta.xml
<CustomField>
    <fullName>Reading_16__c</fullName>
    <label>Reading 16</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_17__c.field-meta.xml
<CustomField>
    <fullName>Reading_17__c</fullName>
    <label>Reading 17</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_18__c.field-meta.xml
<CustomField>
    <fullName>Reading_18__c</fullName>
    <label>Reading 18</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_19__c.field-meta.xml
<CustomField>
    <fullName>Reading_19__c</fullName>
    <label>Reading 19</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_1__c.field-meta.xml
<CustomField>
    <fullName>Reading_1__c</fullName>
    <label>Reading 1</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_20__c.field-meta.xml
<CustomField>
    <fullName>Reading_20__c</fullName>
    <label>Reading 20</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_21__c.field-meta.xml
<CustomField>
    <fullName>Reading_21__c</fullName>
    <label>Reading 21</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_22__c.field-meta.xml
<CustomField>
    <fullName>Reading_22__c</fullName>
    <label>Reading 22</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_23__c.field-meta.xml
<CustomField>
    <fullName>Reading_23__c</fullName>
    <label>Reading 23</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_24__c.field-meta.xml
<CustomField>
    <fullName>Reading_24__c</fullName>
    <label>Reading 24</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_25__c.field-meta.xml
<CustomField>
    <fullName>Reading_25__c</fullName>
    <label>Reading 25</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_26__c.field-meta.xml
<CustomField>
    <fullName>Reading_26__c</fullName>
    <label>Reading 26</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_27__c.field-meta.xml
<CustomField>
    <fullName>Reading_27__c</fullName>
    <label>Reading 27</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_28__c.field-meta.xml
<CustomField>
    <fullName>Reading_28__c</fullName>
    <label>Reading 28</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_29__c.field-meta.xml
<CustomField>
    <fullName>Reading_29__c</fullName>
    <label>Reading 29</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_2__c.field-meta.xml
<CustomField>
    <fullName>Reading_2__c</fullName>
    <label>Reading 2</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_30__c.field-meta.xml
<CustomField>
    <fullName>Reading_30__c</fullName>
    <label>Reading 31</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_31__c.field-meta.xml
<CustomField>
    <fullName>Reading_31__c</fullName>
    <label>Reading 31</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_32__c.field-meta.xml
<CustomField>
    <fullName>Reading_32__c</fullName>
    <label>Reading 32</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_33__c.field-meta.xml
<CustomField>
    <fullName>Reading_33__c</fullName>
    <label>Reading 33</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_34__c.field-meta.xml
<CustomField>
    <fullName>Reading_34__c</fullName>
    <label>Reading 34</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_35__c.field-meta.xml
<CustomField>
    <fullName>Reading_35__c</fullName>
    <label>Reading 35</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_36__c.field-meta.xml
<CustomField>
    <fullName>Reading_36__c</fullName>
    <label>Reading 36</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_37__c.field-meta.xml
<CustomField>
    <fullName>Reading_37__c</fullName>
    <label>Reading 37</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_38__c.field-meta.xml
<CustomField>
    <fullName>Reading_38__c</fullName>
    <label>Reading 38</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_39__c.field-meta.xml
<CustomField>
    <fullName>Reading_39__c</fullName>
    <label>Reading 39</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_3__c.field-meta.xml
<CustomField>
    <fullName>Reading_3__c</fullName>
    <label>Reading 3</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_40__c.field-meta.xml
<CustomField>
    <fullName>Reading_40__c</fullName>
    <label>Reading 40</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_41__c.field-meta.xml
<CustomField>
    <fullName>Reading_41__c</fullName>
    <label>Reading 41</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_42__c.field-meta.xml
<CustomField>
    <fullName>Reading_42__c</fullName>
    <label>Reading 42</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_43__c.field-meta.xml
<CustomField>
    <fullName>Reading_43__c</fullName>
    <label>Reading 43</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_44__c.field-meta.xml
<CustomField>
    <fullName>Reading_44__c</fullName>
    <label>Reading 44</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_45__c.field-meta.xml
<CustomField>
    <fullName>Reading_45__c</fullName>
    <label>Reading 45</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_46__c.field-meta.xml
<CustomField>
    <fullName>Reading_46__c</fullName>
    <label>Reading 46</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_47__c.field-meta.xml
<CustomField>
    <fullName>Reading_47__c</fullName>
    <label>Reading 47</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_48__c.field-meta.xml
<CustomField>
    <fullName>Reading_48__c</fullName>
    <label>Reading 48</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_4__c.field-meta.xml
<CustomField>
    <fullName>Reading_4__c</fullName>
    <label>Reading 4</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_5__c.field-meta.xml
<CustomField>
    <fullName>Reading_5__c</fullName>
    <label>Reading 5</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_6__c.field-meta.xml
<CustomField>
    <fullName>Reading_6__c</fullName>
    <label>Reading 6</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_7__c.field-meta.xml
<CustomField>
    <fullName>Reading_7__c</fullName>
    <label>Reading 7</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_8__c.field-meta.xml
<CustomField>
    <fullName>Reading_8__c</fullName>
    <label>Reading 8</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_9__c.field-meta.xml
<CustomField>
    <fullName>Reading_9__c</fullName>
    <label>Reading 9</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

CVDEV/force-app/main/default/objects/Customer_Reading__c/fields/Reading_Type__c.field-meta.xml
<CustomField>
    <fullName>Reading_Type__c</fullName>
    <label>Reading Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generation</fullName>
            </value>
            <value>
                <fullName>Consumption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CVDEV/force-app/main/default/classes/DecodeNEM12File1.cls
public class DecodeNEM12File1 implements Database.Batchable<Sobject>{
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        String query;
        query='SELECT Id,VersionData from ContentVersion limit 1';
        return database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc,List<ContentVersion> atlist){
        if(atlist==null || (atlist!=null && atlist.isEmpty())){
            return;
        }
        try{
            String blobvalue;
            ContentVersion at= new ContentVersion();
            at=atlist[0];
            blobvalue = at.VersionData.toString();
            String[] splitString=blobvalue.split('\n200,');
            List<Customer_Reading__c> cusReading = new List<Customer_Reading__c>();
            Map<String,String[]> customerMap = new Map<String,String[]>();
            for(String s:splitString){
                if(customerMap.containsKey(s.left(10))){
                    String[] tempAr = customerMap.get(s.left(10));
                    tempAr.add(s);
                    customerMap.put(s.left(10),tempAr);    
                }
                else{
                    if(!s.startsWith('100'))
                        customerMap.put(s.left(10),new String[]{s});   
                }
            }
            For(String customerId: customerMap.keySet()){
                for(String genOrConsum: customerMap.get(customerId)){
                    System.debug('list---->'+genOrConsum);
                    if(genOrConsum.split(',')[3] == 'B1'){
                        System.debug('genOrConsum---->'+genOrConsum);
                        cusReading.addAll(createReading(genOrConsum,true,customerId));
                    }else if(genOrConsum.split(',')[3] == 'E1'){
                        System.debug('Consum---->'+genOrConsum);
                        cusReading.addAll(createReading(genOrConsum,false,customerId));
                    }
                } 
                
            }
            //insert cusReading;
        }
        catch(Exception e){
            system.debug('Exception occured =='+e.getMessage());
            system.debug('Exception line =='+e.getLineNumber());
            system.debug('Exception cause =='+e.getCause());
        }
    }
    
    public List<Customer_Reading__c> createReading(String genOrConsum, Boolean isGeneration,String customerId){
        
        List<Customer_Reading__c> readingList = new List<Customer_Reading__c>();
        for(String dailydata : genOrConsum.split('\n')){           
            Customer_Reading__c cr = new Customer_Reading__c();
            cr.Customer_Id__c=customerId;
            System.debug('isGeneration'+isGeneration);
            cr.reading_type__c=isGeneration?'Generation':'Consumption';
            
            System.debug('reading_type__c'+cr.reading_type__c);
            if(dailydata.startsWith('300')){
                String[] crData=dailydata.split(',');
                //System.debug('crData--->'+crData);
                cr.start_date__c=Date.newInstance(Integer.valueOf(crData[1].left(4)),Integer.valueOf(crData[1].mid(4,2)), Integer.valueOf(crData[1].right(2)));
                cr.Reading_1__c=Decimal.valueOf(crData[2]);
                cr.Reading_2__c=Decimal.valueOf(crData[3]);
                cr.Reading_3__c=Decimal.valueOf(crData[4]);
                cr.Reading_4__c=Decimal.valueOf(crData[5]);
                cr.Reading_5__c=Decimal.valueOf(crData[6]);
                cr.Reading_6__c=Decimal.valueOf(crData[7]);
                cr.Reading_7__c=Decimal.valueOf(crData[8]);
                cr.Reading_8__c=Decimal.valueOf(crData[9]);
                cr.Reading_9__c=Decimal.valueOf(crData[10]);
                cr.Reading_10__c=Decimal.valueOf(crData[11]);
                cr.Reading_11__c=Decimal.valueOf(crData[12]);
                cr.Reading_12__c=Decimal.valueOf(crData[13]);
                cr.Reading_13__c=Decimal.valueOf(crData[14]);
                cr.Reading_14__c=Decimal.valueOf(crData[15]);
                cr.Reading_15__c=Decimal.valueOf(crData[16]);
                cr.Reading_16__c=Decimal.valueOf(crData[17]);
                cr.Reading_17__c=Decimal.valueOf(crData[18]);
                cr.Reading_18__c=Decimal.valueOf(crData[19]);
                cr.Reading_19__c=Decimal.valueOf(crData[20]);
                cr.Reading_20__c=Decimal.valueOf(crData[21]);
                cr.Reading_21__c=Decimal.valueOf(crData[22]);
                cr.Reading_22__c=Decimal.valueOf(crData[23]);
                cr.Reading_23__c=Decimal.valueOf(crData[24]);
                cr.Reading_24__c=Decimal.valueOf(crData[25]);
                cr.Reading_25__c=Decimal.valueOf(crData[26]);
                cr.Reading_26__c=Decimal.valueOf(crData[27]);
                cr.Reading_27__c=Decimal.valueOf(crData[28]);
                cr.Reading_28__c=Decimal.valueOf(crData[29]);
                cr.Reading_29__c=Decimal.valueOf(crData[30]);
                cr.Reading_30__c=Decimal.valueOf(crData[31]);
                cr.Reading_31__c=Decimal.valueOf(crData[32]);
                cr.Reading_32__c=Decimal.valueOf(crData[33]);
                cr.Reading_33__c=Decimal.valueOf(crData[34]);
                cr.Reading_34__c=Decimal.valueOf(crData[35]);
                cr.Reading_35__c=Decimal.valueOf(crData[36]);
                cr.Reading_36__c=Decimal.valueOf(crData[37]);
                cr.Reading_37__c=Decimal.valueOf(crData[38]);
                cr.Reading_38__c=Decimal.valueOf(crData[39]);
                cr.Reading_39__c=Decimal.valueOf(crData[40]);
                cr.Reading_40__c=Decimal.valueOf(crData[41]);
                cr.Reading_41__c=Decimal.valueOf(crData[42]);
                cr.Reading_42__c=Decimal.valueOf(crData[43]);
                cr.Reading_43__c=Decimal.valueOf(crData[44]);
                cr.Reading_44__c=Decimal.valueOf(crData[45]);
                cr.Reading_45__c=Decimal.valueOf(crData[46]);
                cr.Reading_46__c=Decimal.valueOf(crData[47]);
                cr.Reading_47__c=Decimal.valueOf(crData[48]);
                cr.Reading_48__c=Decimal.valueOf(crData[49]);
                readingList.add(cr);
            }
        }     
        System.debug('readingList---->'+readingList);
        System.debug('readingList size---->'+readingList.size());
        return readingList;
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
}